# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven - Cucumber - Selenium (Chrome headless)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (with Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'   # cache de dependencias de Maven

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
          install-dependencies: true
          # Nota: dejamos que WebDriverManager gestione el chromedriver

      - name: Verify Chrome
        run: |
          google-chrome --version || chrome --version || true

      # Usa el wrapper si lo tienes en el repo; si no, sustituye por "mvn"
      - name: Build & test
        run: |
          if [ -x "./mvnw" ]; then
            ./mvnw -B -ntp clean test
          else
            mvn -B -ntp clean test
          fi

      - name: Publica Cucumber JSON como artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json
          path: target/cucumber-reports/Cucumber.json
